### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ddshan** [spurra/vae-hands-3d#6]
`Traceback (most recent call last):
  File "evaluate_model_nono.py", line 118, in <module>
    coords_3D, _, _ = VAE_RGB(img_crop_var, VAE_3D, hand_side_var)
  File "/home/dandans/anaconda3/envs/vae/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "models/model_noHandInvar_noScaleInvar/source_files/models.py", line 372, in forward
    mu, logvar = self.encode(x, hand_side)
  File "models/model_noHandInvar_noScaleInvar/source_files/models.py", line 359, in encode
    h_i = self.encoder(x, hand_side)
  File "/home/dandans/anaconda3/envs/vae/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "models/model_noHandInvar_noScaleInvar/source_files/models.py", line 138, in forward
    x = self.conv1(x)
  File "/home/dandans/anaconda3/envs/vae/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dandans/anaconda3/envs/vae/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/dandans/anaconda3/envs/vae/lib/python3.5/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)

RuntimeError: `CUDNN_STATUS_EXECUTION_FAILED`

Does anyone meet the same problem?

**Comment by spurra** [comment]
This seems to be an issue with your pytorch version. It works fine on my end.

**Comment by ddshan** [comment]
Thanks. Yes it is and already fix this.
